<a href="https://colab.research.google.com/github/techbarik/CodingInterview/blob/main/SpamEmailClassification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importing Library**

In [133]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

**Importing Dataset**

In [134]:
df = pd.read_csv('https://raw.githubusercontent.com/nikhilkr29/Email-Spam-Classifier-using-Naive-Bayes/main/emails.csv')

In [135]:
print(df)

                                                   text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5728 rows x 2 columns]


**Analysis of dataset**

In [ ]:
df.describe()

spam
count  5728.000000
mean      0.238827
std       0.426404
min       0.000000
25%       0.000000
50%       0.000000
75%       0.000000
max       1.000000

In [ ]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5728 entries, 0 to 5727
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   text    5728 non-null   object
 1   spam    5728 non-null   int64 
dtypes: int64(1), object(1)
memory usage: 89.6+ KB


In [ ]:
ham_df = df[df['spam'] == 0]
spam_df = df[df['spam'] == 1]

In [ ]:
ham_df

text  spam
1368  Subject: hello guys ,  i ' m " bugging you " f...     0
1369  Subject: sacramento weather station  fyi  - - ...     0
1370  Subject: from the enron india newsdesk - jan 1...     0
1371  Subject: re : powerisk 2001 - your invitation ...     0
1372  Subject: re : resco database and customer capt...     0
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[4360 rows x 2 columns]

In [ ]:
spam_df

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
1363  Subject: are you ready to get it ?  hello !  v...     1
1364  Subject: would you like a $ 250 gas card ?  do...     1
1365  Subject: immediate reply needed  dear sir ,  i...     1
1366  Subject: wanna see me get fisted ?  fist  bang...     1
1367  Subject: hot stock info : drgv announces anoth...     1

[1368 rows x 2 columns]

In [ ]:
print('Spam Percentage =',(len(spam_df)/len(df))*100,'%')
print('Ham Percentage =',(len(ham_df)/len(df))*100,'%')

Spam Percentage = 23.88268156424581 %
Ham Percentage = 76.11731843575419 %


**Counting Spam and Ham Email in the Dataset**

In [ ]:
df['spam'].value_counts()

0    4360
1    1368
Name: spam, dtype: int64

**Dropping duplicates**

In [ ]:
df.drop_duplicates(inplace = True)

**Checking Missing Data**

In [ ]:
df.isnull().sum()

text    0
spam    0
dtype: int64

**Separating Spam and Not Spam**

In [ ]:
x = df.text.values
y = df.spam.values

**Splitting Dataset**

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size = 0.2)

**Data Preprocessing**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv = CountVectorizer()
x_train = cv.fit_transform(xtrain)

In [ ]:
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

**ML Algorithm**

In [ ]:
from sklearn.naive_bayes import MultinomialNB

In [ ]:
model = MultinomialNB()
model.fit(x_train, ytrain)

In [ ]:
x_test = cv.transform(xtest)

In [ ]:
x_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [2, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
model.score(x_test, ytest)

0.9929762949956101

In [ ]:
emails = ["hey, i'm looking for machine learning tutorial in bengali language", "Hey you win an iphone x giveway for free please send me your address to the survey"]

In [ ]:
cv_emails = cv.transform(emails)

In [ ]:
result = model.predict(cv_emails)
result

array([0, 1])

**Printing the result**

In [ ]:
index = 0
for i in result:
  email = emails[index];
  status = "Spam" if (i == 0) else "Not Spam/Ham"
  print("Classified as: ", status, ", Email: ", email)
  index += 1

Classified as:  Spam , Email:  hey, i'm looking for machine learning tutorial in bengali language
Classified as:  Not Spam/Ham , Email:  Hey you win an iphone x giveway for free please send me your address to the survey


**# The End**